### PR TITLE
feat(workers): set compatibility date to current date

### LINKED ISSUE #58: npm create hono@latest sets compatibility date in the past in wrangler.toml
### What version of Hono are you using?

create-hono version 0.9.3

### What runtime/platform is your app running on?

Cloudflare Workers

### What steps can reproduce the bug?

npm create hono@latest my-hono-project
select "cloudflare workers" 
go to wrangler.toml

### What is the expected behavior?

compatibility date is set to current date

### What do you see instead?

compatibility_date = "2023-12-01"

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by MathurAditya724**
Closes #58 

Updates the `compatibility_date` in the Workers `wrangler.toml` file to the current date.

### CODE REVIEW

**Comment by MathurAditya724** [comment]
@yusukebe you can have a look

**Comment by yusukebe** [comment]
@MathurAditya724 

Wow, ultra fast. Looks good but can you add tests?

**Comment by MathurAditya724** [comment]
Added tests, please check

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
@MathurAditya724 

Awesome work! I'll merge this and release a new version. Thanks!

**Pull request merged**
