### PR TITLE
feat: automate installing dependencies

### PR DESCRIPTION
**Pull request by neutrino2211**
Addresses #18

### CODE REVIEW

**Comment by neutrino2211** [comment]
It works in principle but I am unable to understand the testing setup, so I unfortunately could not write tests

**Comment by yusukebe** [comment]
Hi @neutrino2211 !

Super cool! I've tried it on my machine, and the command works well. Feeling good! I have some thoughts for it.

## Feature Requests

### 1. Defaults to the package manager that executed create-hono

I don't know if this can be done, but for example, if you run `npm create hono`, it would be cool if `npm` was the default package manager among the choices!

### 2. Change the directory

I think I'd be happier to be in the directory I created when the command finishes.

## Testing

Yeah, I know testing it is difficult, but If we can, we should do it.

@sor4chi Do you have any idea how to test this?

**Comment by yutakobayashidev** [comment]
I was reading the create-next-app code a while ago and noticed that I can get the package manager in `process.env.npm_config_user_agent`.

https://github.com/vercel/next.js/blob/8d28d5954e98060e3a478c6b82acb0fb11c5d6f2/packages/create-next-app/helpers/get-pkg-manager.ts

**Comment by yusukebe** [comment]
@yutakobayashidev Nice! Then, we can do it.

**Comment by neutrino2211** [comment]
Great, I'll make those changes

**Comment by neutrino2211** [comment]
@yusukebe It seems like it is impossible to change the directory of the underlying shell

https://stackoverflow.com/questions/19803748/change-working-directory-in-my-current-shell-context-when-running-node-script

Although, I feel like a little message that says "To get started, run: cd _project-dir_ && _package-manager_ dev" after everything is done would be a good compromise

**Comment by yusukebe** [comment]
@neutrino2211 

> Although, I feel like a little message that says "To get started, run: cd _project-dir_ && _package-manager_ dev" after everything is done would be a good compromise

Sounds great! Let's go with it.

**Comment by neutrino2211** [comment]
@yusukebe I'm just noticing that the getting started commands for templates are not uniform across the board, so we won't be able to give users a specific command to run. And editing all templates to have some sort of conformity might be overkill for such a simple message.

I want to suggest leaving it as a TODO or opening a new issue for it.

**Comment by yusukebe** [comment]
> I want to suggest leaving it as a TODO or opening a new issue for it.

Okay! This relates to the future of create-hono. I have some thoughts, which I will present later.

In this case, I think it is enough to just display "*cd*" to the target directory.

**Comment by neutrino2211** [comment]
Took a while to understand how to use execa with vitest but it's all looking good now. The tests run for each package manager and the existence of a package manager specific lock file is checked

**Comment by yusukebe** [comment]
@neutrino2211 

Oops, it still fails. And, in the last step, please run `yarn lint:fix && yarn format:fix` to lint and format.

**Comment by neutrino2211** [comment]
@yusukebe

There seems to be no format:fix command, just lint:fix. Is format:fix supposed to be a prettier command? If so I can add it as a script, run it then push.

**Comment by yusukebe** [comment]
> There seems to be no format:fix command, just lint:fix. Is format:fix supposed to be a prettier command? If so I can add it as a script, run it then push.

Ah, sorry! Yeah, the command is `prettier --write`.

**Comment by neutrino2211** [comment]
Done, everything seems ok 👌

**Comment by yusukebe** [comment]
@neutrino2211 

Thank you! But, CI is still failing.

Do you know the reason?
https://github.com/honojs/create-hono/actions/runs/8012129779/job/21887011694?pr=20

**Comment by neutrino2211** [comment]
Oh, I see the problem. The package manager detection fails sometimes and I don't catch the errors.

Sorry for all the back and forth, I'll make changes and push.

**Comment by neutrino2211** [comment]
@yusukebe 

I think this is it, crossed fingers 🤞

**Comment by yusukebe** [comment]
@neutrino2211 

Super cool! Awesome work!

Then, let's land it! Thank you very much!

**Pull request merged**
