### PR TITLE
feat: added support for external templates

### LINKED ISSUE #62: feat: support for external templates
Can we add support for `--template` or something through which we can use external templates?

This is how the usage will be `pnpm create hono@latest --template=repo_addr`. I understand that we can use `degit` but it's mainly useful because of the hooks.

If you want I can create the PR for this

### PR DESCRIPTION
**Pull request by MathurAditya724**
Closed #62 

- [x] removed the statement that checks if the template is one of the pre-defined ones.
- [x] Taking the provided template repo and passing it in `giget`
- [x] Added a warning banner when using an external template
- [x] minor change - added `node:` in front of `fs` and `path`

I am not parsing the provided template URL because 
- We will lose the `giget` feature of downloading templates using `json` and `tarball` urls.
- I'm not sure about this, but they also have an internal registry that devs might want to use.

Let me know if you don't want these, I can create the logic for parsing the URLs.

@ryuapp can you take a look at the warning message

### CODE REVIEW

**Comment by ryuapp** [comment]
It's slow timing to have those warning messages while downloading, so a warning message should be shown before the download. Also, I don't really know how to run it, so could you please tell me how to run it?

I have one more question. As I commented there(https://github.com/honojs/create-hono/issues/62#issuecomment-2266371296), I'm a little negative about this feature. Is it necessary to create an external template with `create-hono` without recommending with other ways? I would like to know why this feature is good for users.

**Comment by yusukebe** [comment]
> 1. `create-hono` has built-in hooks which is useful, especially for Cloudflare-related templates, it just reduces the number of steps to start using the template.

Regarding this, the [`create-cloudflare` command](https://developers.cloudflare.com/pages/get-started/c3/) already supports external templates. So you can use it.

```bash
npm create cloudflare my-project -- --template git@github.com:user/repo
```

**Comment by MathurAditya724** [comment]
> Regarding this, the [`create-cloudflare` command](https://developers.cloudflare.com/pages/get-started/c3/) already supports external templates. So you can use it.
> 
> ```shell
> npm create cloudflare my-project -- --template git@github.com:user/repo
> ```

That's why I am asking: Why are we also not doing this?

I believe adding this feature will significantly increase the circulation of examples within the community, encouraging more people to start using the [Hono Examples](https://github.com/honojs/examples/) and other third-party ones. This will make it much easier for users to get started.

**Comment by yusukebe** [comment]
I'm not excited about this feature.

> That's why I am asking: Why are we also not doing this?

This is because the function is out of the scope of `create-hono`. I also thought about the same function supporting external projects ago, but I never did that. Because it might have maintenance costs and something like security risks. We have `degit` or `giget`. And if you want to modify `wrangler.toml` when creating a new project, you can use `create-cloudflare`.

**Comment by MathurAditya724** [comment]
Thanks for the clarity on this. I understand the concerns regarding scope and maintenance. I'll go ahead and close this PR.

**Comment by yusukebe** [comment]
@MathurAditya724 

Thank you!

**Pull request closed without merging**
