### PR TITLE
feat(dependencies): show only installed package managers in choices

### PR DESCRIPTION
**Pull request by 6km**
Check if the package manager is installed by running its command with `--version`, and only show installed package managers in choices.

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @6km 

This is awesome!

Looks good, but can we write the test for this feature? It's ok to go without a test if it's super difficult, but I want to check if the choices appear properly.

**Comment by 6km** [comment]
@yusukebe I couldn't figure out a good way to add tests for this feature.

**Comment by 6km** [comment]
By the way, I have improved the package manager detection in dependencies.test.ts.

**Comment by 6km** [comment]
@yusukebe I have tested this locally with node, pnpm and yarn. Can you test if it can detect bun?

**Comment by yusukebe** [comment]
Hi @6km 

Yes. It can detect `bun`! I think we can go with this without adding more tests. Is this ready to merge?

**Comment by 6km** [comment]
Hi @yusukebe

Yes. It's ready to merge! 🚀

**Review by yusukebe — APPROVED** [review]

**Comment by yusukebe** [comment]
@6km 

Let's gooo! Thanks!

**Comment by 6km** [comment]
@yusukebe You're welcome. More contributions coming in the future, insha'allah.

**Pull request merged**
