### PR TITLE
fix: :bug: ensure process exits after copying project files

### PR DESCRIPTION
**Pull request by blazeshomida**
- :bug: Added `process.exit(0)` to cleanly terminate the Node.js process once project files are copied.
- :white_check_mark: Prevents hanging processes after file operations are complete.

### CODE REVIEW

**Comment by yusukebe** [comment]
Hi @blazeshomida 

If the current code is not good for me, can I reproduce it?

**Comment by blazeshomida** [comment]
@yusukebe Sorry I'm not sure I understand the question. However, when running the cli without the `process.exit(0)` the process just hangs. I need to manually press `ctrl+c` to kill the process. If you run the cli currently (without the `process.exit(0)`) you'll see the script hang on completion.

**Comment by yusukebe** [comment]
@blazeshomida 

Thank you for the response, and sorry for my bad explanation.

> If you run the cli currently (without the `process.exit(0)`) you'll see the script hang on completion.

On my machine, this behavior does not occur, and it works well. 

If your problem will be solved with this PR, it's okay to merge. But, I'd like to reproduce the problem in my environment.

**Comment by blazeshomida** [comment]
@yusukebe 
I'm sorry, after more testing, I notice that the script is only hanging when using the `deno run` command. I tried running it with `pnpm` then picking the `deno` template and it works. I think the issue is with Deno and not Hono. I apologize. I thought that it was something simple, turn's out it wasn't 😅.

**Comment by yusukebe** [comment]
@blazeshomida 

I see! No problem. Closing this issue.

**Comment by yusukebe** [comment]
Hey @blazeshomida 

Now reopened. Let's merge it to resolve this issue: https://github.com/honojs/hono/issues/3528, though it's a Deno-side matter.

**Pull request merged**
