### PR TITLE
feat: switched from tiged to giget

### LINKED ISSUE #50: Stop using `tiged`
Currently `create-hono` uses `tiged` to download templates, but since this is not dynamic and the data size is small, it would be better to include the templates themselves in `create-hono`. This change would reduce package size and speed up project generation. It may be necessary to automatically update the package to match the template updates, but this is enough work to be worth the effect and I can make it myself.
If we plan to support 3rd-party repositories as templates in the future it makes sense to continue to rely on tiged. However, it is safe to assume that users with such advanced usage already have the `git` command installed; [the create-remix implementation](https://github.com/remix-run/remix/blob/e324b3e08c83f561f386bdc4a836308cd5249271/packages/create-remix/copy-template.ts#L181-L208) that downloads Github repositories as a zip can also be referenced.

### PR DESCRIPTION
**Pull request by MathurAditya724**
Closes #50 

- Removed `tiged`
- Added `giget`
- Replaced `tiged` function with `downloadTemplate`
- Minor string formatting change

### CODE REVIEW

**Review by goisaki — APPROVED** [review]
Looks good. Nice!

**Comment by MathurAditya724** [comment]
I do have 1 suggestion in place of keeping `offline` (prev `cache`) false all the time, we can give this control to the user by `--offline=false`. This can be a separate PR because we will need to introduce something like `commander`, which can help keep track of these params as well as the show `--help` options.

**Review by yusukebe — APPROVED** [review]
LGTM!

**Comment by yusukebe** [comment]
Hi @MathurAditya724 

Awesome work! I've tried it on my machine; it works well. The fantastic thing is that the time spent `Cloning the template` has been shorter than the current one. It will be fast! I'll merge this now. Thank you very much.

> I do have 1 suggestion in place of keeping `offline` (prev `cache`) false all the time, we can give this control to the user by `--offline=false`. This can be a separate PR because we will need to introduce something like `commander`, which can help keep track of these params as well as the show `--help` options.

Also, I like this idea.

**Pull request merged**
