### PR TITLE
feat: Use `@clack/core` instead of `@inquirer/*`

### PR DESCRIPTION
**Pull request by goisaki**
This PR changes `@inquirer/*` and `nanospinner` to `@clack/core` and custom implementation.
It would improve installation size and speed.

Related: #66

### CODE REVIEW

**Comment by yusukebe** [comment]
@goisaki 

If it's ready, please ping me!

**Comment by goisaki** [comment]
It is ready now!
I will now add a test for itself and mock for the other tests.
Make sure it looks and works.

@yusukebe @MathurAditya724 @ryuapp and others, if you have time please review!

**Comment by goisaki** [comment]
Oops, that didn't make sense.
@yusukebe, should we close this or just replace it?

Screenshot 2024-09-08 at 15 34 07

**Comment by yusukebe** [comment]
@goisaki OOOps. Just a moment.

**Comment by yusukebe** [comment]
@goisaki 

Hmmmm. Unfortunately, I think it's better to keep the current implementation.

**Comment by yusukebe** [comment]
@goisaki 

Thank you for taking your time!

**Pull request closed without merging**
